### ISSUE TITLE
Add NLNet sponsorship acknowledgement to footer

### ISSUE THREAD

**Issue by ronaldtse** [confium/confium.org#3]
Something like this: https://nlnet.nl/project/RNPConfium

<img width="615" alt="Screenshot 2021-11-04 at 10 17 32 AM" src="https://user-images.githubusercontent.com/11865/140246503-828b2bdf-23a7-4e91-b0dc-7b61d02dac9d.png">

**Comment by ronaldtse** [comment]
Here's the text to paste:

This project was funded through the [NGI0 PET Fund](https://nlnet.nl/PET), a fund established by NLnet with financial support from the European Commission's [Next Generation Internet](https://ngi.eu/) programme, under the aegis of DG Communications Networks, Content and Technology under grant agreement No 825310.

**Comment by ronaldtse** [comment]
@strogonoff could you please help add this? We're using Aperis for this site. Thanks!

**Comment by ronaldtse** [comment]
Ping @strogonoff

**Comment by strogonoff** [comment]
1. Repository data layout was upgraded to be editable with current version of Aperis extension for Paneron

2. Repository build code was switched to 1.0.25 react-static plugin that supports new file layout for page illustrations/media (https://github.com/aperis-docs/react-static-plugin-aperis-doc-pages/commit/86a750de401b591b0c8253286a3d12189f183cfc)

    Now, Aperis (beta42) & Paneron (beta19) could be used to edit site contents.

3. On the main page, using Aperis & Paneron, sponsor org logos & supporting text were added as regular figures followed by text paragraph.

    Layout is a bit awkward, since adding logos as figures/illustrations means they show up a bit large. This could be addressed in two ways:

    - Supporting more ways of adding & styling images in any page content (this would compromise semantics), or
    - Add functionality specifically for keeping & displaying sponsor data separately from page content (filed https://github.com/aperis-docs/react-static-plugin-aperis-doc-pages/issues/10 for this)

**Comment by ronaldtse** [comment]
Thank you @strogonoff , confirm that the message is added. Feel free to close this and move any remaining tasks to new tickets.
